version: "3"

services:

  dataskipper_db:
    image: timescale/timescaledb-ha:pg16
    platform: linux/amd64
    environment:
      POSTGRES_HOST: $DB_HOST
      POSTGRES_DB: dataskipper_db
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    container_name: dataskipper_db
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol: