version: "3"

services:

  dataskipper_db:
    image: timescale/timescaledb-ha:pg16
    platform: linux/amd64
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_DB: dataskipper_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    container_name: dataskipper_db
    ports:
      - "5439:5432"
    volumes:
      - db_vol:/var/lib/postgresql/data

volumes:
  db_vol: