# Generated by Django 5.0.3 on 2024-04-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=1024)),
                (
                    "origin",
                    models.IntegerField(
                        choices=[
                            (1, "Power Consumption"),
                            (2, "Power Distribution"),
                            (3, "Water"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "graph_type",
                    models.IntegerField(
                        choices=[(1, "Line"), (2, "Bar"), (3, "Pie")], default=1
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("voltage_rms", "Voltage Rms"),
                            ("current_rms", "Current Rms"),
                            ("voltage_peak", "Voltage Peak"),
                            ("current_peak", "Current Peak"),
                            ("phase", "Phase"),
                            ("voltage_frequency", "Voltage Frequency"),
                            ("power", "Power"),
                            ("energy", "Energy"),
                            ("flow_rate", "Flow Rate"),
                            ("volume", "Volume"),
                        ],
                        default="voltage_rms",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
            ],
        ),
    ]
