# Generated by Django 5.0.3 on 2024-04-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=1024)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("electrical_distribution", "Electrical Distribution"),
                            ("electrical_generation", "Electrical Generation"),
                            ("water_distribution", "Water Distribution"),
                            ("water_generation", "Water Generation"),
                        ],
                        default="electrical_distribution",
                    ),
                ),
                ("graph_type", models.CharField(max_length=256)),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("voltage_rms", "Voltage Rms"),
                            ("current_rms", "Current Rms"),
                            ("voltage_peak", "Voltage Peak"),
                            ("current_peak", "Current Peak"),
                            ("voltage_frequency", "Voltage Frequency"),
                            ("power", "Power"),
                            ("energy", "Energy"),
                            ("flow_rate", "Flow Rate"),
                            ("volume", "Volume"),
                        ],
                        default="voltage_rms",
                    ),
                ),
                ("order", models.IntegerField(default=1)),
                ("client", models.JSONField()),
                ("tag", models.IntegerField(null=True)),
            ],
        ),
    ]
