# Generated by Django 5.0.3 on 2024-04-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="client",
            field=models.JSONField(null=True),
        ),
    ]
