# Generated by Django 5.0.3 on 2024-04-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_config_origin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="graph_type",
            field=models.CharField(max_length=256),
        ),
    ]
