# Generated by Django 5.0.3 on 2024-04-30 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_alter_config_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="organization_id",
            field=models.CharField(default="iit-jammu", max_length=1024),
        ),
    ]
