# Generated by Django 5.0.3 on 2024-04-17 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_config_graph_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="metric",
            field=models.CharField(
                choices=[
                    ("voltage_rms", "Voltage Rms"),
                    ("current_rms", "Current Rms"),
                    ("voltage_peak", "Voltage Peak"),
                    ("current_peak", "Current Peak"),
                    ("voltage_frequency", "Voltage Frequency"),
                    ("power", "Power"),
                    ("energy", "Energy"),
                    ("flow_rate", "Flow Rate"),
                    ("volume", "Volume"),
                ],
                default="voltage_rms",
            ),
        ),
    ]
