# Generated by Django 5.0.3 on 2024-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_config_organization_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="config",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
