# Generated by Django 5.0.3 on 2024-04-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.CharField(max_length=256)),
                ("organization_label", models.CharField(max_length=256)),
                ("block_id", models.CharField(max_length=256)),
                ("block_label", models.CharField(max_length=256)),
                ("panel_id", models.CharField(max_length=256)),
                ("panel_label", models.CharField(max_length=256)),
                ("phase_id", models.CharField(max_length=256)),
                ("phase_label", models.CharField(max_length=256)),
                ("client_id", models.CharField(max_length=256)),
                ("client_label", models.CharField(max_length=256)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("electrical_distribution", "Electrical Distribution"),
                            ("electrical_generation", "Electrical Generation"),
                            ("water_distribution", "Water Distribution"),
                            ("water_generation", "Water Generation"),
                        ],
                        default="electrical_distribution",
                    ),
                ),
                ("description", models.CharField(max_length=1024, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_faulty", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ElectricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.TextField()),
                ("timestamp", models.IntegerField()),
                ("voltage_rms", models.FloatField()),
                ("current_rms", models.FloatField()),
                ("voltage_peak", models.FloatField(null=True)),
                ("current_peak", models.FloatField(null=True)),
                ("phase", models.FloatField()),
                ("voltage_frequency", models.FloatField()),
                ("power", models.FloatField()),
                ("energy", models.FloatField()),
                ("watt_hour", models.FloatField(null=True)),
                ("total_watts", models.FloatField(null=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="WaterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=56)),
                ("timestamp", models.IntegerField()),
                ("flow_rate", models.FloatField()),
                ("time_window_in_seconds", models.IntegerField()),
                ("volume", models.FloatField()),
                (
                    "rate_unit",
                    models.CharField(
                        choices=[("sec", "Sec"), ("min", "Min"), ("hour", "Hour")],
                        default="sec",
                    ),
                ),
                (
                    "volume_unit",
                    models.CharField(
                        choices=[("ml", "Ml"), ("l", "L"), ("kl", "Kl")], default="ml"
                    ),
                ),
            ],
        ),
    ]
