# Generated by Django 5.0.3 on 2024-03-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=56)),
                ("generation_timestamp", models.IntegerField()),
                ("voltage_RMS", models.FloatField()),
                ("current_RMS", models.FloatField()),
                ("voltage_peak", models.FloatField(null=True)),
                ("current_peak", models.FloatField(null=True)),
                ("phase", models.FloatField()),
                ("voltage_frequency", models.FloatField()),
                ("power", models.FloatField()),
                ("energy", models.FloatField()),
                ("watt_hour", models.FloatField(null=True)),
                ("total_watts", models.FloatField(null=True)),
                ("delete_status", models.BooleanField(default=False)),
            ],
        ),
    ]
