# Generated by Django 5.0.3 on 2024-03-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalogger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WaterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=56)),
                ("generation_timestamp", models.IntegerField()),
                ("flow_rate", models.FloatField()),
                ("time_window_in_seconds", models.IntegerField()),
                ("volume", models.FloatField()),
            ],
        ),
    ]
