# Generated by Django 5.0.3 on 2024-04-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalogger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientdata",
            name="latitude",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="clientdata",
            name="longitude",
            field=models.FloatField(null=True),
        ),
    ]
