# Generated by Django 5.0.3 on 2024-03-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalogger", "0002_waterdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricaldata",
            name="client_id",
            field=models.TextField(),
        ),
    ]
