# Generated by Django 5.0.3 on 2024-04-07 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("datalogger", "0003_alter_electricaldata_client_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organisation_id", models.CharField(max_length=256)),
                ("block_id", models.CharField(max_length=256)),
                ("panel_id", models.CharField(max_length=256)),
                ("level_id", models.CharField(max_length=256)),
                ("phase_id", models.CharField(max_length=256)),
                ("client_id", models.CharField(max_length=256)),
                ("description", models.CharField(max_length=1024, null=True)),
                ("tags", models.CharField(max_length=1024, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_faulty", models.BooleanField(default=False)),
            ],
        ),
    ]
