# Generated by Django 5.0.3 on 2024-04-07 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datalogger", "0004_clientdata"),
    ]

    operations = [
        migrations.RenameField(
            model_name="electricaldata",
            old_name="current_RMS",
            new_name="current_rms",
        ),
        migrations.RenameField(
            model_name="electricaldata",
            old_name="generation_timestamp",
            new_name="timestamp",
        ),
        migrations.RenameField(
            model_name="electricaldata",
            old_name="voltage_RMS",
            new_name="voltage_rms",
        ),
    ]
