# Generated by Django 5.0.3 on 2024-04-16 01:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("datalogger", "0006_rename_generation_timestamp_waterdata_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clientdata",
            old_name="organisation_id",
            new_name="organization_id",
        ),
    ]
