# Generated by Django 5.0.3 on 2024-04-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="token",
            field=models.CharField(default=None, max_length=1024),
            preserve_default=False,
        ),
    ]
