# Generated by Django 5.0.3 on 2024-04-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_userprofile_is_verified_userprofile_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="user_type",
            field=models.IntegerField(
                choices=[
                    (1, "Admin"),
                    (2, "Facility Manager"),
                    (3, "Facility Staff"),
                    (4, "End User"),
                ],
                default=1,
            ),
        ),
    ]
